pipeline {
    agent { label 'ubuntu-docker' }

    environment { 
        PROJECTNAME = 'my_web_blog'
    }

    triggers { pollSCM('2 * * * *') }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }

    stages {

        stage('Delete workspace before build starts') {
            steps {
                echo 'Deleting workspace'
                deleteDir()
            }
        }
        
        stage('Checkout') {
            steps{
                git branch: 'master',
                    url: 'https://github.com/soloma70/my_site.git/'        
                }
        }
        
        stage('Test') {
            steps{
                sh 'ls -la'
                sh 'pwd'
            }
        }
        
        stage("Login to DockerHub") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-soloma', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                }
            }
        }

        stage('Build Docker image') {
            steps{
                sh 'docker build -t $USERNAME/$PROJECTNAME:v1.${BUILD_NUMBER} .'
                sh 'docker images'
            }
        }
        
        stage('Push Docker image to DockerHub') {
            steps{
                sh 'docker login -u $USERNAME --password $PASSWORD'
                sh 'docker push $USERNAME/$PROJECTNAME:v1.${BUILD_NUMBER}'
            }
        }
        
        stage('Delete Docker image locally') {
            steps{
                sh 'docker rmi $(docker images -a -q)'
                sh 'docker images'
            }
        }
    }
}