pipeline {
    agent { label 'ubuntu-terraform' }
    environment { 
        AWS_SHARED_CREDENTIALS_FILE='./.cred/aws'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    
    stages {
        
        stage('Raise IaaC & SaaC') {
            when {
                expression { params.choice_path == "Raise" }
            }

            stages {
/* ---------------------- Preparation Workspase -------------------------- */
/*                stage('Prepare') {
                    steps {
                        echo 'Deleting workspace'
                        deleteDir()
                    }
                }
*/
/* --------------------------- Clone Git Repo ----------------------------- */
                stage('Clone Repo') {
                    steps{
                        git branch: 'master',
                            url: 'https://github.com/soloma70/ans_tf.git'        
                        }
                }
/* ---------------- Raising the infrastructure on AWS --------------------- */
                stage('Init') {
                    steps{
                        sh 'terraform init -reconfigure -no-color'
                    }
                }
                stage('Plan') {
                    steps {
                        sh 'terraform plan -no-color'
                    }
                }
                stage('Validate Apply') {
                    input {
                        message "Do you want to apply this plan?"
                        ok "Apply plan"
                    }
                    steps {
                        echo 'Apply Accepted'
                    }
                }
                stage('Deploy') {
                    steps {
                        sh 'terraform apply -auto-approve -no-color'
                    }
                }
/* --------------------- Wait to Up EC2 Instance -------------------------- */
                stage('EC2 Wait') {
                    steps {
                        sh '''aws ec2 wait instance-status-ok \\
                        --instance-ids $(terraform output -raw webapp_i_id) \\
                        --region $(terraform output -raw webapp_region)'''
                    }
                }
/* --------------- Installing the software on the Server ------------------- */  
                stage('Validate Ansible') {
                    input {
                        message "Do you want to run Ansible?"
                        ok "Run Ansible"
                    }
                    steps {
                        echo 'Ansible Approved'
                        }
                }
                stage('Add Host') {
                    steps {
                        sh '''
                        printf "\\n$(terraform output -raw elastic_ip)\\n" > hosts
                        cat hosts
                        '''
                    }
                }

                stage('Ansible') {
                    steps {
                        ansiblePlaybook(credentialsId: 'aws_deploy_iaac', inventory: 'hosts', playbook: 'playbook.yml')
                    }
                }
            }
        }

        stage('Destroy IaaC') {
            when {
                expression { params.choice_path == "Destroy" }
            }

            stages {            
/* ------------------ Destroy the infrastructure on AWS ------------------- */  
                stage('Validate Destroy') {
                    input {
                        message "Do you want to destroy?"
                        ok "Destroy"
                        }
                    steps {
                        echo 'Destroy Approved'
                    }
                }
                stage('Destroy') {
                    steps {
                        sh 'terraform destroy -auto-approve -no-color'
                    }
                }
            }
        }
    }
}
